// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.3
// Project name: SquareLine_Project_POPRAWKI

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
lv_obj_t * ui_Screen1;
void ui_event_Screen1_Button3(lv_event_t * e);
lv_obj_t * ui_Screen1_Button3;
lv_obj_t * ui_Screen1_Label11;
void ui_event_Screen1_Button1(lv_event_t * e);
lv_obj_t * ui_Screen1_Button1;
lv_obj_t * ui_Screen1_Label12;
lv_obj_t * ui_Screen1_Label13;
lv_obj_t * ui_Screen1_Label14;
void ui_event_Screen1_Button2(lv_event_t * e);
lv_obj_t * ui_Screen1_Button2;
lv_obj_t * ui_Screen1_Label15;
lv_obj_t * ui_Bar2;
lv_obj_t * ui_Label4;
void ui_event_Screen1_Button4(lv_event_t * e);
lv_obj_t * ui_Screen1_Button4;
lv_obj_t * ui_Screen1_Label16;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Screen1_Label1;
lv_obj_t * ui_Screen1_Label2;
lv_obj_t * ui_Screen1_Label3;
lv_obj_t * ui_Screen1_Label4;
lv_obj_t * ui_Screen1_Label5;
lv_obj_t * ui_Screen1_Label6;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Bar3;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Bar1;
lv_obj_t * ui_Screen1_Label8;
lv_obj_t * ui_Screen1_Label9;
lv_obj_t * ui_Screen1_Label10;
lv_obj_t * ui_Screen1_Label7;
lv_obj_t * ui_Bar4;
lv_obj_t * ui_Label28;
lv_obj_t * ui_Screen2;
void ui_event_Screen2_Button1(lv_event_t * e);
lv_obj_t * ui_Screen2_Button1;
lv_obj_t * ui_Screen2_Label2;
lv_obj_t * ui_Label32;
lv_obj_t * ui_Screen3;
void ui_event_Screen2_Button2(lv_event_t * e);
lv_obj_t * ui_Screen2_Button2;
lv_obj_t * ui_Screen3_Keyboard1;
lv_obj_t * ui_Screen3_TextArea2;
lv_obj_t * ui_Screen3_TextArea1;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label1;
void ui_event_Dropdown4(lv_event_t * e);
lv_obj_t * ui_Dropdown4;
lv_obj_t * ui_Label31;
lv_obj_t * ui_Screen4;
lv_obj_t * ui_Keyboard1;
lv_obj_t * ui_TextArea1;
lv_obj_t * ui_TextArea2;
lv_obj_t * ui_TextArea3;
lv_obj_t * ui_TextArea4;
lv_obj_t * ui_TextArea5;
lv_obj_t * ui_Label2;
void ui_event_Screen2_Button3(lv_event_t * e);
lv_obj_t * ui_Screen2_Button3;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label30;
lv_obj_t * ui_Screen5;
lv_obj_t * ui_Chart1;
void ui_event_Dropdown2(lv_event_t * e);
lv_obj_t * ui_Dropdown2;
void ui_event_Dropdown1(lv_event_t * e);
lv_obj_t * ui_Dropdown1;
void ui_event_Screen2_Button4(lv_event_t * e);
lv_obj_t * ui_Screen2_Button4;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Label19;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Label21;
lv_obj_t * ui_Label22;
lv_obj_t * ui_Label23;
lv_obj_t * ui_Label24;
lv_obj_t * ui_Label25;
lv_obj_t * ui_Label26;
lv_obj_t * ui_Label27;
lv_obj_t * ui_Label29;
lv_obj_t * ui_Screen6;
lv_obj_t * ui_Spinner2;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Bar11;
lv_obj_t * ui_Label62;
void ui_event_Screen6_Button1(lv_event_t * e);
lv_obj_t * ui_Screen6_Button1;
lv_obj_t * ui_Label61;
lv_obj_t * ui_Screen7;
lv_obj_t * ui_Spinner1;
lv_obj_t * ui_Label8;
lv_obj_t * ui____initial_actions0;
lv_coord_t ui_Chart1_series_1_array[96] = {0};
lv_chart_series_t * ui_Chart1_series_1;


///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen1_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0);
    }
}
void ui_event_Screen1_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(ui_Screen7, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0);
        skanuj_wifi(e);
    }
}
void ui_event_Screen1_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0);
    }
}
void ui_event_Screen1_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(ui_Screen5, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0);
    }
    if(event_code == LV_EVENT_CLICKED) {
    	rysuj_wielkosc(e);
    }
}
void ui_event_Screen2_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0);
    }
}
void ui_event_Screen2_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0);
    }
}
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        laduj_wifi(e);
    }
}
void ui_event_Dropdown4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        wifi_type(e);
    }
}
void ui_event_Screen2_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0);
    }
}
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        laduj_tekst(e);
    }
}
void ui_event_Dropdown2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        rysuj_wielkosc(e);
    }
}
void ui_event_Dropdown1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        rysuj_wielkosc(e);
        (e);
    }
}
void ui_event_Screen2_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0);
    }
}
static void ta_event_cb(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * ta = lv_event_get_target(e);
    if(code == LV_EVENT_CLICKED || code == LV_EVENT_FOCUSED) {
        /*Focus on the clicked text area*/
        if(ui_Screen3_Keyboard1 != NULL) lv_keyboard_set_textarea(ui_Screen3_Keyboard1, ta);
    }

    else if(code == LV_EVENT_READY) {
        LV_LOG_USER("Ready, current text: %s", lv_textarea_get_text(ta));
    }
}
static void ta_event_cb_2(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * ta = lv_event_get_target(e);
    if(code == LV_EVENT_CLICKED || code == LV_EVENT_FOCUSED) {
        /*Focus on the clicked text area*/
        if(ui_Screen3_Keyboard1 != NULL) lv_keyboard_set_textarea(ui_Keyboard1, ta);
    }

    else if(code == LV_EVENT_READY) {
        LV_LOG_USER("Ready, current text: %s", lv_textarea_get_text(ta));
    }
}
void ui_event_Screen6_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0);
        stop_wifi_change(e);
    }
}
///////////////////// SCREENS ////////////////////
void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1_Button3 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Button3, 68);
    lv_obj_set_height(ui_Screen1_Button3, 26);
    lv_obj_set_x(ui_Screen1_Button3, -38);
    lv_obj_set_y(ui_Screen1_Button3, 101);
    lv_obj_set_align(ui_Screen1_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1_Button3, lv_color_hex(0x3E3E3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1_Button3, lv_color_hex(0x0BE900), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Screen1_Button3, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Screen1_Label11 = lv_label_create(ui_Screen1_Button3);
    lv_obj_set_width(ui_Screen1_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label11, 0);
    lv_obj_set_y(ui_Screen1_Label11, -1);
    lv_obj_set_align(ui_Screen1_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label11, "terminal");

    ui_Screen1_Button1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Button1, 68);
    lv_obj_set_height(ui_Screen1_Button1, 26);
    lv_obj_set_x(ui_Screen1_Button1, -114);
    lv_obj_set_y(ui_Screen1_Button1, 101);
    lv_obj_set_align(ui_Screen1_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1_Button1, lv_color_hex(0x3E3E3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1_Button1, lv_color_hex(0x0BE900), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Screen1_Button1, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Screen1_Label12 = lv_label_create(ui_Screen1_Button1);
    lv_obj_set_width(ui_Screen1_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen1_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label12, "wifi");

    ui_Screen1_Label13 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label13, 0);
    lv_obj_set_y(ui_Screen1_Label13, -107);
    lv_obj_set_align(ui_Screen1_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label13, "20:20:20");
    lv_label_set_recolor(ui_Screen1_Label13, "true");
    lv_obj_set_style_text_font(ui_Screen1_Label13, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label14 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label14, 0);
    lv_obj_set_y(ui_Screen1_Label14, -80);
    lv_obj_set_align(ui_Screen1_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label14, "Data");

    ui_Screen1_Button2 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Button2, 68);
    lv_obj_set_height(ui_Screen1_Button2, 26);
    lv_obj_set_x(ui_Screen1_Button2, 38);
    lv_obj_set_y(ui_Screen1_Button2, 101);
    lv_obj_set_align(ui_Screen1_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1_Button2, lv_color_hex(0x3E3E3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1_Button2, lv_color_hex(0x0BE900), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Screen1_Button2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Screen1_Label15 = lv_label_create(ui_Screen1_Button2);
    lv_obj_set_width(ui_Screen1_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen1_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label15, "czas");

    ui_Bar2 = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_Bar2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar2, 47);
    lv_obj_set_height(ui_Bar2, 10);
    lv_obj_set_x(ui_Bar2, 134);
    lv_obj_set_y(ui_Bar2, -114);
    lv_obj_set_align(ui_Bar2, LV_ALIGN_CENTER);

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 136);
    lv_obj_set_y(ui_Label4, -101);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "-");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Button4 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Button4, 68);
    lv_obj_set_height(ui_Screen1_Button4, 26);
    lv_obj_set_x(ui_Screen1_Button4, 114);
    lv_obj_set_y(ui_Screen1_Button4, 101);
    lv_obj_set_align(ui_Screen1_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1_Button4, lv_color_hex(0x3E3E3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1_Button4, lv_color_hex(0x0BE900), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Screen1_Button4, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Screen1_Label16 = lv_label_create(ui_Screen1_Button4);
    lv_obj_set_width(ui_Screen1_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen1_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label16, "wykresy");

    ui_Label7 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -131);
    lv_obj_set_y(ui_Label7, -107);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Pomiar");
    lv_obj_set_style_bg_color(ui_Label7, lv_color_hex(0xE16666), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 151);
    lv_obj_set_height(ui_Panel1, 129);
    lv_obj_set_x(ui_Panel1, -77);
    lv_obj_set_y(ui_Panel1, 10);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Screen1_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label1, -42);
    lv_obj_set_y(ui_Screen1_Label1, -20);
    lv_obj_set_align(ui_Screen1_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label1, "temp.");
    lv_obj_set_style_text_font(ui_Screen1_Label1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label2 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Screen1_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label2, -41);
    lv_obj_set_y(ui_Screen1_Label2, -47);
    lv_obj_set_align(ui_Screen1_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label2, "cisni.");
    lv_obj_set_style_text_font(ui_Screen1_Label2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label3 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Screen1_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label3, -41);
    lv_obj_set_y(ui_Screen1_Label3, 7);
    lv_obj_set_align(ui_Screen1_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label3, "wilg.");
    lv_obj_set_style_text_font(ui_Screen1_Label3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label4 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Screen1_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label4, 29);
    lv_obj_set_y(ui_Screen1_Label4, -20);
    lv_obj_set_align(ui_Screen1_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label4, "-");
    lv_obj_set_style_text_font(ui_Screen1_Label4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label5 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Screen1_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label5, 29);
    lv_obj_set_y(ui_Screen1_Label5, -47);
    lv_obj_set_align(ui_Screen1_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label5, "-");
    lv_obj_set_style_text_font(ui_Screen1_Label5, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label6 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Screen1_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label6, 29);
    lv_obj_set_y(ui_Screen1_Label6, 7);
    lv_obj_set_align(ui_Screen1_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label6, "-");
    lv_obj_set_style_text_font(ui_Screen1_Label6, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -41);
    lv_obj_set_y(ui_Label14, 35);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "smog");
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar3 = lv_bar_create(ui_Panel1);
    lv_bar_set_value(ui_Bar3, 0, LV_ANIM_OFF);
    lv_bar_set_range(ui_Bar3, 0, 660);
    lv_obj_set_width(ui_Bar3, 110);
    lv_obj_set_height(ui_Bar3, 8);
    lv_obj_set_x(ui_Bar3, 1);
    lv_obj_set_y(ui_Bar3, 56);
    lv_obj_set_align(ui_Bar3, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Bar3, lv_color_hex(0x00FF29), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 29);
    lv_obj_set_y(ui_Label15, 35);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "-");
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 110);
    lv_obj_set_y(ui_Label10, 44);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "-");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label11, 142);
    lv_obj_set_height(ui_Label11, 3);
    lv_obj_set_x(ui_Label11, 80);
    lv_obj_set_y(ui_Label11, 68);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "_");
    lv_obj_set_style_bg_color(ui_Label11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label5, 4);
    lv_obj_set_height(ui_Label5, 90);
    lv_obj_set_x(ui_Label5, 11);
    lv_obj_set_y(ui_Label5, 22);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, ".");
    lv_obj_set_style_bg_color(ui_Label5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label12, 4);
    lv_obj_set_height(ui_Label12, 90);
    lv_obj_set_x(ui_Label12, 149);
    lv_obj_set_y(ui_Label12, 22);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, ".");
    lv_obj_set_style_bg_color(ui_Label12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image2, &ui_img_313407983);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 155
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 44
    lv_obj_set_x(ui_Image2, 79);
    lv_obj_set_y(ui_Image2, -43);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 44);
    lv_obj_set_y(ui_Label6, 44);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "CO2");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar1 = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_bar_set_range(ui_Bar1, 0, 2500);
    lv_obj_set_width(ui_Bar1, 110);
    lv_obj_set_height(ui_Bar1, 8);
    lv_obj_set_x(ui_Bar1, 79);
    lv_obj_set_y(ui_Bar1, 60);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0x24FF25), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Screen1_Label8 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label8, 44);
    lv_obj_set_y(ui_Screen1_Label8, -10);
    lv_obj_set_align(ui_Screen1_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label8, "temp.");
    lv_obj_set_style_text_font(ui_Screen1_Label8, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label9 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label9, 110);
    lv_obj_set_y(ui_Screen1_Label9, 17);
    lv_obj_set_align(ui_Screen1_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label9, "-");
    lv_obj_set_style_text_font(ui_Screen1_Label9, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label10 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label10, 110);
    lv_obj_set_y(ui_Screen1_Label10, -10);
    lv_obj_set_align(ui_Screen1_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label10, "-");
    lv_obj_set_style_text_font(ui_Screen1_Label10, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label7 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label7, 44);
    lv_obj_set_y(ui_Screen1_Label7, 17);
    lv_obj_set_align(ui_Screen1_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label7, "wilg.");
    lv_obj_set_style_text_font(ui_Screen1_Label7, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar4 = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_Bar4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar4, 47);
    lv_obj_set_height(ui_Bar4, 10);
    lv_obj_set_x(ui_Bar4, 134);
    lv_obj_set_y(ui_Bar4, -88);
    lv_obj_set_align(ui_Bar4, LV_ALIGN_CENTER);

    ui_Label28 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, 136);
    lv_obj_set_y(ui_Label28, -75);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, " - ");
    lv_obj_set_style_text_font(ui_Label28, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen1_Button3, ui_event_Screen1_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1_Button1, ui_event_Screen1_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1_Button2, ui_event_Screen1_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1_Button4, ui_event_Screen1_Button4, LV_EVENT_ALL, NULL);

}
void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen2_Button1 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Screen2_Button1, 21);
    lv_obj_set_height(ui_Screen2_Button1, 20);
    lv_obj_set_x(ui_Screen2_Button1, 147);
    lv_obj_set_y(ui_Screen2_Button1, -107);
    lv_obj_set_align(ui_Screen2_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen2_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen2_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen2_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen2_Button1, lv_color_hex(0xEA3E3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen2_Button1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Screen2_Button1, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Screen2_Label2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Screen2_Label2, 304);
    lv_obj_set_height(ui_Screen2_Label2, 200);
    lv_obj_set_x(ui_Screen2_Label2, 0);
    lv_obj_set_y(ui_Screen2_Label2, 6);
    lv_obj_set_align(ui_Screen2_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen2_Label2, "brak wiadomosci");
    lv_obj_set_style_text_align(ui_Screen2_Label2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen2_Label2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label32, 147);
    lv_obj_set_y(ui_Label32, -107);
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "X");

    lv_obj_add_event_cb(ui_Screen2_Button1, ui_event_Screen2_Button1, LV_EVENT_ALL, NULL);

}
void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen2_Button2 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Screen2_Button2, 21);
    lv_obj_set_height(ui_Screen2_Button2, 20);
    lv_obj_set_x(ui_Screen2_Button2, 147);
    lv_obj_set_y(ui_Screen2_Button2, -107);
    lv_obj_set_align(ui_Screen2_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen2_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen2_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen2_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen2_Button2, lv_color_hex(0xEA3E3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen2_Button2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Screen2_Button2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Screen3_Keyboard1 = lv_keyboard_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3_Keyboard1, 300);
    lv_obj_set_height(ui_Screen3_Keyboard1, 120);
    lv_obj_set_x(ui_Screen3_Keyboard1, 0);
    lv_obj_set_y(ui_Screen3_Keyboard1, 53);
    lv_obj_set_align(ui_Screen3_Keyboard1, LV_ALIGN_CENTER);

    ui_Screen3_TextArea2 = lv_textarea_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3_TextArea2, 260);
    lv_obj_set_height(ui_Screen3_TextArea2, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_x(ui_Screen3_TextArea2, -17);
    lv_obj_set_y(ui_Screen3_TextArea2, -63);
    lv_obj_set_align(ui_Screen3_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_Screen3_TextArea2, 128);
    lv_textarea_set_placeholder_text(ui_Screen3_TextArea2, "Wprowadz nazwe sieci lub wybierz");
    lv_textarea_set_one_line(ui_Screen3_TextArea2, true);
    lv_obj_add_event_cb(ui_Screen3_TextArea2, ta_event_cb, LV_EVENT_ALL, NULL);

    lv_obj_set_style_text_font(ui_Screen3_TextArea2, &lv_font_montserrat_12, LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Screen3_TextArea2, &lv_font_montserrat_12,
                             LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_Screen3_TextArea1 = lv_textarea_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3_TextArea1, 151);
    lv_obj_set_height(ui_Screen3_TextArea1, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_x(ui_Screen3_TextArea1, -74);
    lv_obj_set_y(ui_Screen3_TextArea1, -25);
    lv_obj_set_align(ui_Screen3_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_Screen3_TextArea1, 128);
    lv_textarea_set_placeholder_text(ui_Screen3_TextArea1, "Wprowadz haslo");
    lv_textarea_set_password_mode(ui_Screen3_TextArea1, true);
    lv_obj_add_event_cb(ui_Screen3_TextArea1, ta_event_cb, LV_EVENT_ALL, NULL);

    lv_obj_set_style_text_font(ui_Screen3_TextArea1, &lv_font_montserrat_12, LV_PART_CURSOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Screen3_TextArea1, &lv_font_montserrat_12,
                             LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button1, 116);
    lv_obj_set_height(ui_Button1, 27);
    lv_obj_set_x(ui_Button1, 70);
    lv_obj_set_y(ui_Button1, -26);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "enter");

    ui_Dropdown4 = lv_dropdown_create(ui_Screen3);
    lv_dropdown_set_options(ui_Dropdown4, "");
    lv_obj_set_width(ui_Dropdown4, 260);
    lv_obj_set_height(ui_Dropdown4, 24);
    lv_obj_set_x(ui_Dropdown4, -17);
    lv_obj_set_y(ui_Dropdown4, -102);
    lv_obj_set_align(ui_Dropdown4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Dropdown4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Dropdown4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Dropdown4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Dropdown4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Dropdown4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Dropdown4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Dropdown4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_letter_space(lv_dropdown_get_list(ui_Dropdown4), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(lv_dropdown_get_list(ui_Dropdown4), 6,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown4), &lv_font_montserrat_14,
                             LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(lv_dropdown_get_list(ui_Dropdown4), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(lv_dropdown_get_list(ui_Dropdown4), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown4), &lv_font_montserrat_14,
                             LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, 147);
    lv_obj_set_y(ui_Label31, -107);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "X");

    lv_obj_add_event_cb(ui_Screen2_Button2, ui_event_Screen2_Button2, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Screen3_Keyboard1, ui_Screen3_TextArea2);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown4, ui_event_Dropdown4, LV_EVENT_ALL, NULL);

}
void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Keyboard1 = lv_keyboard_create(ui_Screen4);
    lv_keyboard_set_mode(ui_Keyboard1, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard1, 300);
    lv_obj_set_height(ui_Keyboard1, 120);
    lv_obj_set_x(ui_Keyboard1, 2);
    lv_obj_set_y(ui_Keyboard1, 53);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    ui_TextArea1 = lv_textarea_create(ui_Screen4);
    lv_obj_set_width(ui_TextArea1, 44);
    lv_obj_set_height(ui_TextArea1, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_TextArea1, -7);
    lv_obj_set_y(ui_TextArea1, -42);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea1, 2);
    lv_textarea_set_placeholder_text(ui_TextArea1, "DD");
    lv_textarea_set_one_line(ui_TextArea1, true);
    lv_obj_set_style_bg_color(ui_TextArea1, lv_color_hex(0xFFFFFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_TextArea1, ta_event_cb_2, LV_EVENT_ALL, NULL);

    ui_TextArea2 = lv_textarea_create(ui_Screen4);
    lv_obj_set_width(ui_TextArea2, 44);
    lv_obj_set_height(ui_TextArea2, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_TextArea2, 44);
    lv_obj_set_y(ui_TextArea2, -43);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea2, 2);
    lv_textarea_set_placeholder_text(ui_TextArea2, "MM");
    lv_textarea_set_one_line(ui_TextArea2, true);
    lv_obj_add_event_cb(ui_TextArea2, ta_event_cb_2, LV_EVENT_ALL, NULL);

    ui_TextArea3 = lv_textarea_create(ui_Screen4);
    lv_obj_set_width(ui_TextArea3, 52);
    lv_obj_set_height(ui_TextArea3, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_TextArea3, 97);
    lv_obj_set_y(ui_TextArea3, -43);
    lv_obj_set_align(ui_TextArea3, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea3, 4);
    lv_textarea_set_placeholder_text(ui_TextArea3, "YYYY");
    lv_textarea_set_one_line(ui_TextArea3, true);
    lv_obj_add_event_cb(ui_TextArea3, ta_event_cb_2, LV_EVENT_ALL, NULL);

    ui_TextArea4 = lv_textarea_create(ui_Screen4);
    lv_obj_set_width(ui_TextArea4, 44);
    lv_obj_set_height(ui_TextArea4, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_TextArea4, -7);
    lv_obj_set_y(ui_TextArea4, -88);
    lv_obj_set_align(ui_TextArea4, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea4, 2);
    lv_textarea_set_placeholder_text(ui_TextArea4, "HH");
    lv_textarea_set_one_line(ui_TextArea4, true);
    lv_obj_add_event_cb(ui_TextArea4, ta_event_cb_2, LV_EVENT_ALL, NULL);

    ui_TextArea5 = lv_textarea_create(ui_Screen4);
    lv_obj_set_width(ui_TextArea5, 44);
    lv_obj_set_height(ui_TextArea5, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_TextArea5, 44);
    lv_obj_set_y(ui_TextArea5, -88);
    lv_obj_set_align(ui_TextArea5, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea5, 2);
    lv_textarea_set_placeholder_text(ui_TextArea5, "MM");
    lv_textarea_set_one_line(ui_TextArea5, true);
    lv_obj_add_event_cb(ui_TextArea5, ta_event_cb_2, LV_EVENT_ALL, NULL);

    ui_Label2 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -97);
    lv_obj_set_y(ui_Label2, -67);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "wprowadz czas:\n\n\nwprowadz date");

    ui_Screen2_Button3 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Screen2_Button3, 21);
    lv_obj_set_height(ui_Screen2_Button3, 20);
    lv_obj_set_x(ui_Screen2_Button3, 147);
    lv_obj_set_y(ui_Screen2_Button3, -107);
    lv_obj_set_align(ui_Screen2_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen2_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen2_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen2_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen2_Button3, lv_color_hex(0xEA3E3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen2_Button3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Screen2_Button3, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Button2 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button2, 116);
    lv_obj_set_height(ui_Button2, 27);
    lv_obj_set_x(ui_Button2, 92);
    lv_obj_set_y(ui_Button2, 38);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "enter");

    ui_Label30 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, 147);
    lv_obj_set_y(ui_Label30, -107);
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "X");

    lv_keyboard_set_textarea(ui_Keyboard1, ui_TextArea1);
    lv_obj_add_event_cb(ui_Screen2_Button3, ui_event_Screen2_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);

}
void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Chart1 = lv_chart_create(ui_Screen5);
    lv_obj_set_width(ui_Chart1, 265);
    lv_obj_set_height(ui_Chart1, 169);
    lv_obj_set_x(ui_Chart1, 19);
    lv_obj_set_y(ui_Chart1, -32);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Chart1, 96);
    lv_chart_set_range(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, -5, 100);
    lv_chart_set_range(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, -50, 100);
    lv_chart_set_div_line_count(ui_Chart1, 21, 25);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 10, 5, 25, 1, false, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 30);
    ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x808080), LV_CHART_AXIS_SECONDARY_Y);
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);
    //static lv_coord_t ui_Chart1_series_1_array[] = { -11, -12, -13, -14, -15, -16, -17, -18, -19, -20, -17, -14, -10, -8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 16, 16, 17, 18, 19, 20, 20, 20, 20, 30, 30, 30, 30, 32, 33, 33, 33, 33, 33, 33, 33, 34, 35, 36, 37, 37, 37, 37, 37, 37, 37, 38, 38, 38, 38, 39, 40, 41, 40, 40, 40, 40, 40, 40, 41, 42, 42, 42, 42, 42, 42, 42, 42, 53, 53, 53, 53, 64, 64, 75, 75, 86, 86, 86, 86, 97, 88, 99, 99, 99, 99, 99, 99, 99, 99, 99 };
    //lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);

    lv_obj_set_style_size(ui_Chart1, 2, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Dropdown2 = lv_dropdown_create(ui_Screen5);
    lv_dropdown_set_options(ui_Dropdown2, "wilgot wew\ntemp wew\nco2 wew\nwilgot zew\ntemp zew\ncisnienie zew\nsmog");
    lv_obj_set_width(ui_Dropdown2, 141);
    lv_obj_set_height(ui_Dropdown2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown2, -86);
    lv_obj_set_y(ui_Dropdown2, 96);
    lv_obj_set_align(ui_Dropdown2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Dropdown1 = lv_dropdown_create(ui_Screen5);
    lv_dropdown_set_options(ui_Dropdown1, "dzisiaj\nwczoraj\nprzedwczoraj");
    lv_obj_set_width(ui_Dropdown1, 141);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, 56);
    lv_obj_set_y(ui_Dropdown1, 96);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Screen2_Button4 = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_Screen2_Button4, 21);
    lv_obj_set_height(ui_Screen2_Button4, 20);
    lv_obj_set_x(ui_Screen2_Button4, 144);
    lv_obj_set_y(ui_Screen2_Button4, 101);
    lv_obj_set_align(ui_Screen2_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen2_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen2_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen2_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen2_Button4, lv_color_hex(0xEA3E3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen2_Button4, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Screen2_Button4, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label16 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -103);
    lv_obj_set_y(ui_Label16, 70);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "0");

    ui_Label13 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -82);
    lv_obj_set_y(ui_Label13, 70);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "2");

    ui_Label17 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -63);
    lv_obj_set_y(ui_Label17, 70);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "4");

    ui_Label18 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -42);
    lv_obj_set_y(ui_Label18, 70);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "6");

    ui_Label19 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, -22);
    lv_obj_set_y(ui_Label19, 70);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "8");

    ui_Label20 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 0);
    lv_obj_set_y(ui_Label20, 70);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "10");

    ui_Label21 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 20);
    lv_obj_set_y(ui_Label21, 70);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "12");

    ui_Label22 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, 40);
    lv_obj_set_y(ui_Label22, 70);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "14");

    ui_Label23 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 60);
    lv_obj_set_y(ui_Label23, 70);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "16");

    ui_Label24 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 81);
    lv_obj_set_y(ui_Label24, 70);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "18");

    ui_Label25 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 100);
    lv_obj_set_y(ui_Label25, 70);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "20");

    ui_Label26 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, 121);
    lv_obj_set_y(ui_Label26, 70);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "22");

    ui_Label27 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, 142);
    lv_obj_set_y(ui_Label27, 70);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "24");

    ui_Label29 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, 144);
    lv_obj_set_y(ui_Label29, 101);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "X");

    lv_obj_add_event_cb(ui_Dropdown2, ui_event_Dropdown2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown1, ui_event_Dropdown1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen2_Button4, ui_event_Screen2_Button4, LV_EVENT_ALL, NULL);

}
void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Spinner2 = lv_spinner_create(ui_Screen6, 1000, 90);
    lv_obj_set_width(ui_Spinner2, 80);
    lv_obj_set_height(ui_Spinner2, 80);
    lv_obj_set_x(ui_Spinner2, 0);
    lv_obj_set_y(ui_Spinner2, -32);
    lv_obj_set_align(ui_Spinner2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner2, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 0);
    lv_obj_set_y(ui_Label9, 79);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "konfiguracja stacji i sensora\nmoze to potrwac kilka minut");
    lv_obj_set_style_text_align(ui_Label9, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar11 = lv_bar_create(ui_Screen6);
    lv_bar_set_value(ui_Bar11, 25, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar11, 150);
    lv_obj_set_height(ui_Bar11, 10);
    lv_obj_set_x(ui_Bar11, 0);
    lv_obj_set_y(ui_Bar11, 23);
    lv_obj_set_align(ui_Bar11, LV_ALIGN_CENTER);

    ui_Label62 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label62, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label62, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label62, 0);
    lv_obj_set_y(ui_Label62, 45);
    lv_obj_set_align(ui_Label62, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label62, "100%");

    ui_Screen6_Button1 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_Screen6_Button1, 21);
    lv_obj_set_height(ui_Screen6_Button1, 20);
    lv_obj_set_x(ui_Screen6_Button1, 147);
    lv_obj_set_y(ui_Screen6_Button1, -107);
    lv_obj_set_align(ui_Screen6_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen6_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen6_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen6_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen6_Button1, lv_color_hex(0xEA3E3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen6_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen6_Button1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Screen6_Button1, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label61 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label61, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label61, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label61, 147);
    lv_obj_set_y(ui_Label61, -107);
    lv_obj_set_align(ui_Label61, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label61, "X");

    lv_obj_add_event_cb(ui_Screen6_Button1, ui_event_Screen6_Button1, LV_EVENT_ALL, NULL);

}
void ui_Screen7_screen_init(void)
{
    ui_Screen7 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Spinner1 = lv_spinner_create(ui_Screen7, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 80);
    lv_obj_set_height(ui_Spinner1, 80);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 0);
    lv_obj_set_y(ui_Label8, 75);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "skanuje siec wifi\nczekaj");
    lv_obj_set_style_text_align(ui_Label8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui_Screen4_screen_init();
    ui_Screen5_screen_init();
    ui_Screen6_screen_init();
    ui_Screen7_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);

	update_ui_data();
}
