// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.3
// Project name: SquareLine_Project_POPRAWKI

#ifndef _SQUARELINE_PROJECT_POPRAWKI_UI_H
#define _SQUARELINE_PROJECT_POPRAWKI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../../lvgl/lvgl.h"
#include "main.h"
#include "fr_global.h"
#include "fr_stm32.h"

#include "ui_events.h"
extern lv_obj_t * ui_Screen1;
void ui_event_Screen1_Button3(lv_event_t * e);
extern lv_obj_t * ui_Screen1_Button3;
extern lv_obj_t * ui_Screen1_Label11;
void ui_event_Screen1_Button1(lv_event_t * e);
extern lv_obj_t * ui_Screen1_Button1;
extern lv_obj_t * ui_Screen1_Label12;
extern lv_obj_t * ui_Screen1_Label13;
extern lv_obj_t * ui_Screen1_Label14;
void ui_event_Screen1_Button2(lv_event_t * e);
extern lv_obj_t * ui_Screen1_Button2;
extern lv_obj_t * ui_Screen1_Label15;
extern lv_obj_t * ui_Bar2;
extern lv_obj_t * ui_Label4;
void ui_event_Screen1_Button4(lv_event_t * e);
extern lv_obj_t * ui_Screen1_Button4;
extern lv_obj_t * ui_Screen1_Label16;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Screen1_Label1;
extern lv_obj_t * ui_Screen1_Label2;
extern lv_obj_t * ui_Screen1_Label3;
extern lv_obj_t * ui_Screen1_Label4;
extern lv_obj_t * ui_Screen1_Label5;
extern lv_obj_t * ui_Screen1_Label6;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Bar3;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Screen1_Label8;
extern lv_obj_t * ui_Screen1_Label9;
extern lv_obj_t * ui_Screen1_Label10;
extern lv_obj_t * ui_Screen1_Label7;
extern lv_obj_t * ui_Bar4;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Screen2;
void ui_event_Screen2_Button1(lv_event_t * e);
extern lv_obj_t * ui_Screen2_Button1;
extern lv_obj_t * ui_Screen2_Label2;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Screen3;
void ui_event_Screen2_Button2(lv_event_t * e);
extern lv_obj_t * ui_Screen2_Button2;
extern lv_obj_t * ui_Screen3_Keyboard1;
extern lv_obj_t * ui_Screen3_TextArea2;
extern lv_obj_t * ui_Screen3_TextArea1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
void ui_event_Dropdown4(lv_event_t * e);
extern lv_obj_t * ui_Dropdown4;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_TextArea3;
extern lv_obj_t * ui_TextArea4;
extern lv_obj_t * ui_TextArea5;
extern lv_obj_t * ui_Label2;
void ui_event_Screen2_Button3(lv_event_t * e);
extern lv_obj_t * ui_Screen2_Button3;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Chart1;
void ui_event_Dropdown2(lv_event_t * e);
extern lv_obj_t * ui_Dropdown2;
void ui_event_Dropdown1(lv_event_t * e);
extern lv_obj_t * ui_Dropdown1;
void ui_event_Screen2_Button4(lv_event_t * e);
extern lv_obj_t * ui_Screen2_Button4;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_Spinner2;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Bar11;
extern lv_obj_t * ui_Label62;
void ui_event_Screen6_Button1(lv_event_t * e);
extern lv_obj_t * ui_Screen6_Button1;
extern lv_obj_t * ui_Label61;
extern lv_obj_t * ui_Screen7;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_313407983);    // assets\new_25_04__1_-removebg-preview__1___1_-removebg-preview (1).png

extern lv_coord_t ui_Chart1_series_1_array[96];
extern lv_chart_series_t * ui_Chart1_series_1;
/*
extern TIM_HandleTypeDef htim5;
extern TIM_HandleTypeDef htim9;
extern TIM_HandleTypeDef htim10;
extern TIM_HandleTypeDef htim11;
extern uint32_t color;
extern RTC_TimeTypeDef time_set;
extern RTC_DateTypeDef data_set;
extern uint16_t rok;
extern RTC_HandleTypeDef hrtc;
extern char str_temp[12];
extern char str_cis[12];
extern char str_wil[12];
extern char str_dust[6];
extern char str_CO2[6];
extern char str_temp_in[12];
extern char str_hum_in[12];
extern char czas_str[20];
extern char data_str[40];
extern uint32_t bat_lvl_int;
extern char bat_lvl_lb[7];
extern char wifi_read_ssid[33];
extern char wifi_password[33];
extern uint8_t wifi_set;
extern uint8_t wifi_list_send;
extern uint8_t nie_szuka_wifi;
extern uint8_t screen_change;
extern uint16_t i1;
extern UART_HandleTypeDef huart1;
extern int16_t sensor_data_read[480];
extern uint8_t PomiarFlag;
extern uint32_t gradient_dust;
extern uint32_t gradient_co2;
extern uint16_t dust;
extern uint32_t ra;
extern uint16_t co2_raw;
extern char bat_sen_lvl_lb[7];
*/

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
