// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.3
// Project name: SquareLine_Project_POPRAWKI

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void skanuj_wifi(lv_event_t * e);
void laduj_wifi(lv_event_t * e);
void wifi_type(lv_event_t * e);
void laduj_czas(lv_event_t * e);
void laduj_tekst(lv_event_t * e);
void rysuj_wielkosc(lv_event_t * e);
// Function to load text from user interface and process it
void laduj_tekst(lv_event_t * e);

// Function to check if the date and time values are legitimate
uint8_t isDateTimeLegitimate(RTC_DateTypeDef data_set, RTC_TimeTypeDef time_set, uint8_t* dni, uint16_t rok_temp);

// Function to calculate weekday
uint8_t calculateWeekDay(uint8_t day, uint8_t month, uint16_t year);

// Function to update text color
void updateTextColor(uint32_t color);

void stop_wifi_change(lv_event_t * e);



#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
